# Generated by Django 3.0.2 on 2020-01-24 18:00

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='Actor', max_length=20, verbose_name='имя актера')),
                ('second_name', models.CharField(blank=True, default='Actor', max_length=20, verbose_name='фамилия актера')),
                ('citizen', models.CharField(default='Author', max_length=20, verbose_name='гражданство актера')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='Author', max_length=20, verbose_name='имя')),
                ('second_name', models.CharField(blank=True, default='Author', max_length=20, verbose_name='фамилия')),
                ('citizen', models.CharField(default='Author', max_length=20, verbose_name='гражданство')),
            ],
            options={
                'verbose_name': 'Режисер',
                'verbose_name_plural': 'Режисеры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, verbose_name='название')),
                ('year', models.IntegerField(blank=True, default=2020, verbose_name='год создания')),
                ('city', models.CharField(max_length=20, verbose_name='страна-создатель')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos', verbose_name='фото фасада')),
                ('info', models.TextField(default='', verbose_name='краткая информация о сюжете')),
                ('quality', models.CharField(default='480p', max_length=20, verbose_name='качество видео')),
                ('duration', models.IntegerField(blank=True, default=60, verbose_name='продолжительность фильма')),
                ('rating', models.IntegerField(null=True, verbose_name='колличество звезд')),
                ('video', models.FileField(upload_to='videos', verbose_name='видео файл')),
                ('min_age', models.IntegerField(blank=True, default=18, verbose_name='минимальный возраст')),
                ('actors', models.ManyToManyField(to='films.Actor')),
                ('directors', models.ManyToManyField(to='films.Director')),
                ('genres', models.ManyToManyField(to='films.Genre')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['title'], name='film_name_idx'),
        ),
    ]
