# Generated by Django 3.0.2 on 2020-01-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='имя')),
                ('info', models.TextField(verbose_name='полная информация')),
                ('price', models.IntegerField(blank=True, verbose_name='цена в месяц')),
                ('duration', models.IntegerField(blank=True, verbose_name='продолжительность в месяцах')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'тарифы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='телефон')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='логин')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('age', models.IntegerField(blank=True, verbose_name='возраст')),
            ],
            options={
                'verbose_name': 'Подпосчик',
                'verbose_name_plural': 'подписчики',
            },
        ),
        migrations.CreateModel(
            name='UsedFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='текущий статус')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': 'Используемый фильм',
                'verbose_name_plural': 'используемые фильмы',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='дата совершения')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Tarifs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'сделки',
                'index_together': {('user', 'tarif')},
            },
        ),
    ]
